Repository adjoint-io/fcl, pull requests merged in 2019-08, with the labels that each got.

#35 IsInitialized is not a bounded join semilattice
  src/Language/FCL/Undefinedness.hs
  tests/Test/Undefinedness.hs
Labels: ready to review

#36 Signal failures via appropriate exit code
  exe/Main.hs
Labels: ready to merge

#34 Uplink swagger
  package.yaml
  src/HTTP/FCL/API.hs
  src/HTTP/FCL/SwaggerSchema.hs
  src/Language/FCL/AST.hs
  src/Language/FCL/Contract.hs
  src/Language/FCL/Encoding.hs
  src/Language/FCL/Error.hs
  src/Language/FCL/Key.hs
  src/Language/FCL/Metadata.hs
  src/Language/FCL/Storage.hs
  src/Language/FCL/Typecheck.hs
  tests/Main.hs
  tests/Test/Encoding.hs
  tests/Test/Key.hs
Labels: ready to merge

#38 Update simple example to match documentation
  examples/simple.s
Labels: ready to merge

#33 Revisiting reachability analysis
  exe/Main.hs
  package.yaml
  src/Data/List/List2.hs
  src/HTTP/FCL/SwaggerSchema.hs
  src/Language/FCL/AST.hs
  src/Language/FCL/Analysis.hs
  src/Language/FCL/Compile.hs
  src/Language/FCL/Eval.hs
  src/Language/FCL/Graphviz.hs
  src/Language/FCL/Reachability/Definitions.hs
  src/Language/FCL/Reachability/General.hs
  src/Language/FCL/Reachability/SplitAndMerge.hs
  src/Language/FCL/Reachability/StructuredTransition.hs
  src/Language/FCL/Reachability/Utils.hs
  src/Language/FCL/ReachabilityGraph.hs
  tests/Test/Workflow/Generation/SafeWorkflowNet.hs
  tests/Test/Workflow/Generation/SafeWorkflowNet/Examples.hs
  tests/Test/Workflow/Generation/SafeWorkflowNet/Tests.hs
  tests/Test/Workflow/SafeWorkflow.hs
  tests/Test/Workflow/SafeWorkflow/Examples.hs
  tests/Test/Workflow/SafeWorkflow/Extended.hs
  tests/Test/Workflow/SafeWorkflow/Tests.hs
  tests/Test/Workflow/Soundness.hs
  tests/workflow/negative/boundedness-2.out
  tests/workflow/negative/boundedness.out
  tests/workflow/negative/concurrent-extra-incorrect.out
  tests/workflow/negative/concurrent-non-FC.out
  tests/workflow/negative/deadlock-and-livelock.out
  tests/workflow/negative/graph-AND.out
  tests/workflow/negative/improper-completion.out
  tests/workflow/positive/novation.dot
  tests/workflow/positive/novation.out
  tests/workflow/positive/novation.s
  tests/workflow/positive/xor-and.s
Labels: ready to merge

#40 Undefinedness refactor
  ChangeLog.md
  src/Language/FCL/Undefinedness.hs
  src/Language/FCL/WorkflowNet.hs
  tests/Test/Undefinedness.hs
Labels: ready to review

#42 Generalizing safe workflows
  src/Data/List/List2.hs
  tests/Test/Workflow/SafeWorkflow.hs
  tests/Test/Workflow/SafeWorkflow/Examples.hs
  tests/Test/Workflow/SafeWorkflow/Tests.hs
  tests/Test/Workflow/Soundness.hs
Labels: ready to review, wip

#44 Preliminary work on improving undefined analysis
  exe/Main.hs
  src/Language/FCL/Undefinedness.hs
  src/Language/FCL/WorkflowNet.hs
  tests/Test/Undefinedness.hs
  tests/workflow/negative/one-branch-and-undef.dot
  tests/workflow/negative/one-branch-and-undef.out
  tests/workflow/negative/one-branch-and-undef.s
  tests/workflow/negative/one-branch-undef.dot
  tests/workflow/negative/one-branch-undef.out
  tests/workflow/negative/one-branch-undef.s
  tests/workflow/negative/simple-undef.dot
  tests/workflow/negative/simple-undef.out
  tests/workflow/negative/simple-undef.s
  tests/workflow/positive/simple-def.dot
  tests/workflow/positive/simple-def.out
  tests/workflow/positive/simple-def.s
  tests/workflow/positive/xor-and-defined.dot
  tests/workflow/positive/xor-and-defined.out
  tests/workflow/positive/xor-and-defined.s
  tests/workflow/positive/xor-defined.dot
  tests/workflow/positive/xor-defined.out
  tests/workflow/positive/xor-defined.s
Labels: ready to review, wip

#48 Modernise product contract
  examples/product.s
Labels: ready to review

#47 Move hole (?) into operator token class
  src/Language/FCL/Token.hs
Labels: ready to merge

#23 Mutable helper args
  ChangeLog.md
  src/Language/FCL/Eval.hs
  src/Language/FCL/Typecheck.hs
  tests/eval/positive/modify-record.calls
  tests/eval/positive/modify-record.out
  tests/eval/positive/modify-record.s
  tests/eval/positive/mut-helper-arg.calls
  tests/eval/positive/mut-helper-arg.out
  tests/eval/positive/mut-helper-arg.s
  tests/eval/positive/mut-helper-shadow.calls
  tests/eval/positive/mut-helper-shadow.out
  tests/eval/positive/mut-helper-shadow.s
  tests/script/negative/holes/helper.out
  tests/script/negative/typecheck/new-local-variable-field.out
  tests/script/negative/typecheck/new-local-variable-field.s
  tests/script/negative/typecheck/shadow-case.out
Labels: enhancement, ready to merge

#45 Annotating safe workflows
  package.yaml
  src/Language/FCL/SafeWorkflow.hs
  src/Language/FCL/SafeWorkflow/Simple.hs
  tests/Test/Workflow/SafeWorkflow/Examples.hs
  tests/Test/Workflow/SafeWorkflow/Extended.hs
  tests/Test/Workflow/SafeWorkflow/Tests.hs
Labels: ready to review

#49 Syntax
  ChangeLog.md
  examples/product.s
  src/Language/FCL/AST.hs
  src/Language/FCL/Parser.hs
  tests/eval/positive/elif.calls
  tests/eval/positive/elif.out
  tests/eval/positive/elif.s
Labels: ready to review

#46 Generalise unary negation
  src/Language/FCL/Eval.hs
  src/Language/FCL/Typecheck.hs
  tests/eval/positive/negate.calls
  tests/eval/positive/negate.out
  tests/eval/positive/negate.s
Labels: ready to review
