Repository adjoint-io/fcl, pull requests merged in 2019-07, with the labels that each got.

#8 Generate Swagger specification for a Servant API
  ci/Dockerfile
  cloudbuild.yaml
  examples/counting.s
  http/Main.hs
  http/README.md
  lsp/Main.hs
  package.yaml
  src/HTTP/FCL/API.hs
  src/HTTP/FCL/SwaggerSchema.hs
  src/Language/FCL/AST.hs
  src/Language/FCL/Address.hs
  src/Language/FCL/Analysis.hs
  src/Language/FCL/Compile.hs
  src/Language/FCL/Duplicate.hs
  src/Language/FCL/Effect.hs
  src/Language/FCL/Eval.hs
  src/Language/FCL/Graphviz.hs
  src/Language/FCL/Hash.hs
  src/Language/FCL/LanguageServerProtocol.hs
  src/Language/FCL/Metadata.hs
  src/Language/FCL/Parser.hs
  src/Language/FCL/Prim.hs
  src/Language/FCL/ReachabilityGraph.hs
  src/Language/FCL/Storage.hs
  src/Language/FCL/Typecheck.hs
  src/Language/FCL/Undefinedness.hs
  src/Language/FCL/Warning.hs
  src/Numeric/Lossless/Decimal.hs
  src/Numeric/Lossless/Number.hs
  tests/Main.hs
  tests/TestSwagger.hs
  tests/docker-compose.postgres.yaml
  tests/json/contract.json
  tests/json/storage.json
  tests/script/negative/collections/invalid_transform.out
  tests/script/positive/adt/args.out
  tests/script/positive/adt/args.s
Labels: ready to review

#19 Add information of the calling method in deltas when transferring assets
  src/Language/FCL/Delta.hs
  src/Language/FCL/Eval.hs
  src/Language/FCL/Pretty.hs
  tests/Reference.hs
  tests/TestScript.hs
  tests/eval/positive/swap.calls
  tests/eval/positive/swap.out
  tests/eval/positive/swap.s
Labels: ready to merge

#22 Remove SafeInteger and SafeString modules
  ChangeLog.md
  package.yaml
  src/HTTP/FCL/SwaggerSchema.hs
  src/Language/FCL/AST.hs
  src/Language/FCL/Error.hs
  src/Language/FCL/Eval.hs
  src/Language/FCL/Key.hs
  src/Language/FCL/Parser.hs
  src/Language/FCL/SafeInteger.hs
  src/Language/FCL/SafeString.hs
  src/Language/FCL/Unsafe.hs
  tests/Reference.hs
  tests/TestScript.hs
Labels: ready to merge

#24 Add swagger instances for DateTime and Delta
  src/HTTP/FCL/SwaggerSchema.hs
  src/Language/FCL/AST.hs
Labels: wip

#28 Restructured tests
  src/Language/FCL/AST.hs
  stack.yaml.lock
  tests/Main.hs
  tests/Test/Golden.hs
  tests/Test/Helpers.hs
  tests/Test/Json.hs
  tests/Test/Key.hs
  tests/Test/Number.hs
  tests/Test/Reference.hs
  tests/Test/Script.hs
  tests/Test/Storage.hs
  tests/Test/Swagger.hs
  tests/Test/Undefinedness.hs
  tests/Test/Workflow/Compilation.hs
  tests/Test/Workflow/Generation/SafeWorkflowNet.hs
  tests/Test/Workflow/Generation/SafeWorkflowNet/Examples.hs
  tests/Test/Workflow/Generation/SafeWorkflowNet/Tests.hs
  tests/Test/Workflow/Soundness.hs
  tests/WorkflowGenTests.hs
Labels: ready to merge

#29 Fix GHC warnings
  package.yaml
  src/Language/FCL/AST.hs
  src/Language/FCL/Address.hs
  src/Language/FCL/Debug.hs
  src/Language/FCL/Eval.hs
  src/Language/FCL/Key.hs
  src/Language/FCL/Orphans.hs
  src/Language/FCL/Storage.hs
Labels: ready to review

#30 Export `Typecheck.createADTInfo`
  src/Language/FCL/Typecheck.hs
Labels: ready to merge

#32 Small tweaks
  src/HTTP/FCL/API.hs
  src/HTTP/FCL/SwaggerSchema.hs
  src/Language/FCL/Contract.hs
  src/Language/FCL/Encoding.hs
  src/Language/FCL/Eval.hs
Labels: ready to merge
